<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>acm</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>x86;x64;ARM64</Platforms>
    <PublishTrimmed>false</PublishTrimmed>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
    <VersionPrefix>1.4.1</VersionPrefix>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Certes" Version="3.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\app.ico" />
  </ItemGroup>

  <Target Name="EnsureRuntimeFoldersOnPublish" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)plugins;$(PublishDir)logs;$(PublishDir)certs;$(PublishDir)storage" />
  </Target>
</Project>
